### ISSUE TITLE
Req: PCL (Portable class library) support should be added to Gentoo (or documented if already added)

### ISSUE THREAD

**Issue by ArsenShnurkov** [gentoo/dotnet#111]
Typical compilation error looks like this:

    /usr/lib64/mono/xbuild/12.0/bin/Microsoft.Common.targets:  warning : Unable to find framework corresponding to the target framework moniker '.NETPortable,Version=v4.5,Profile=Profile259'. Framework assembly references will be resolved from the GAC, which might not be the intended behavior.
    /usr/lib64/mono/xbuild/12.0/bin/Microsoft.Common.targets: error : PCL Reference Assemblies not installed.

 you need to have the following installed:
    **Portable Class Library Reference Assemblies.**
    Portable Class Library MSBuild targets.
    Xamarin’s Portable Class Library Profiles.

PCL provides a set of common reference assemblies
http://stackoverflow.com/questions/5238955/what-is-a-portable-class-library
    The following assemblies are available within a Portable Class Library project:
        mscorlib.dll
        System.dll
        System.Core.dll
        System.Xml.dll
        System.ComponentModel.Composition.dll
        System.Net.dll
        System.Runtime.Serialization.dll
        System.ServiceModel.dll
        System.Xml.Serialization.dll
        System.Windows.dll (from Silverlight)

The ZIP file is installed to: %ProgramFiles(x86)%\Microsoft .NET Portable Library Reference Assemblies 4.6 RC.
we released the following portable libraries with our new license, on NuGet.org:
    Async for .NET Framework 4, Silverlight 4 and 5, and Windows Phone 7.5 and 8
    Microsoft ASP.NET SignalR .NET Client
    Microsoft BCL Build Components
    Microsoft BCL Portability Pack
    Microsoft Composition
    Microsoft Compression
    Microsoft HTTP Client Libraries
    Microsoft Immutable Collections
    ODataLib

Some links on topic:
overview of the goal - https://msdn.microsoft.com/en-us/library/gg597391%28v=vs.110%29.aspx
what problem does it solve - http://stackoverflow.com/questions/16338388/what-does-the-portable-class-library-actually-solve
availability (2013-10-14, so gentoo lags for 2 years) - http://blogs.msdn.com/b/dotnet/archive/2013/10/14/portable-class-library-pcl-now-available-on-all-platforms.aspx
binary download from MS - https://www.microsoft.com/en-us/download/details.aspx?id=40727
availability from Xamarin - http://blogs.msdn.com/b/dotnet/archive/2013/11/13/pcl-and-net-nuget-libraries-are-now-enabled-for-xamarin.aspx
introduction from Xamarin - http://developer.xamarin.com/guides/cross-platform/application_fundamentals/pcl/introduction_to_portable_class_libraries/
installation instructions from Xamarin - http://lastexitcode.com/blog/2014/11/16/InstallingPortableClassLibrariesForXamarinStudio/

When you create a ‘regular’ Application Project or a Library Project, the resulting DLL is restricted to working on the specific platform it is created for. 
When you create a Portable Class Library, however, you can choose a combination of platforms that you want your code to run on. The compatibility choices you make when creating a Portable Class Library are translated into a "Profile” identifier, which describes which platforms the library supports.

<img src="http://developer.xamarin.com/guides/cross-platform/application_fundamentals/pcl/introduction_to_portable_class_libraries/Images/image2.png" />

PCL projects target specific profiles that support a known set of BCL classes/features. 
PCL Support was added in Xamarin Studio 4.2. 
Portable Library projects are automatically enabled in Xamarin Studio on OS X (what about gentoo?)
When a PCL is created in Xamarin Studio it is automatically configured with a Profile that works for Xamarin.iOS and Xamarin.Android. 

<img src="http://developer.xamarin.com/guides/cross-platform/application_fundamentals/pcl/introduction_to_portable_class_libraries/Images/image4.png" />

Changing any of these options alters the profile being used by this PCL, which in turn controls what features can be used in the portable code.
Changing any of the Target Framework options automatically updates the Current Profile;

http://stackoverflow.com/questions/27805245

One more introduction -
http://www.codeguru.com/csharp/.net/net_framework/introduction-to-portable-class-library-in-.net-framework-4.5.htm
"Portable Class Library, otherwise called PCL, comes with .NET framework 4.5 RC and a separate project template is available on Visual Studio 2012 RC."

when you create a Portable Class Library then Visual Studio will take care of importing only the supported set of base class libraries that are compatible with the selected platform versions. Even in the referenced base class libraries, only the supported methods or types will be exposed through intellisense.

**Comment by ArsenShnurkov** [comment]
mono instructions - http://www.mono-project.com/docs/getting-started/install/linux/
"just install referenceassemblies-pcl" they say

**Comment by rcarz** [comment]
I'm planning to open a PR for this, coreclr, and corefx if I ever get around to finishing. In the mean time, here's an e-build for the reference assemblies:

dev-dotnet/referenceassemblies-pcl/referenceassemblies-pcl-4.6.ebuild
```bash
# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

inherit rpm

DESCRIPTION=".NET Portable Class Library reference assemblies"
SRC_URI="http://download.mono-project.com/repo/centos/r/referenceassemblies-pcl/referenceassemblies-pcl-${PV}-0.noarch.rpm"

SLOT="0"
KEYWORDS="x86 amd64"
IUSE=""

DEPEND=">=dev-lang/mono-4.0"
RDEPEND="${DEPEND}"

S="${WORKDIR}"

src_install() {
        cp -R "${S}/"* "${D}/" || die "Install failed!"
}
```

**Comment by ArsenShnurkov** [comment]
the goal of gentoo is to build everything from sources (if you don't want why not to use Ubuntu/Fedora then?). [b]This ebuild is usefull[/b], but it doesn't follow gentoo way...

**Comment by rcarz** [comment]
Unfortunately building the entire .NET runtime along with class libraries is not fully supported on Linux yet. You need the PCL reference assemblies to bootstrap the build of corefx.
