### ISSUE TITLE
design bug: egacinstall works incorrectly from pkg_postinst

### ISSUE THREAD

**Issue by ArsenShnurkov** [gentoo/dotnet#112]
If I install binary package, I expect that assembly will be registred in currently selected GAC (if I have several mono versions or nonstandart location of gac, portable mono for example).

Currently egacinstall tries to cheat and register assemblies as regular files through portage mechanism (in src_install)

pkg_preinst function looks even better then pkg_postinst
https://devmanual.gentoo.org/ebuild-writing/functions/pkg_preinst/index.html
but more complicated, because customization should be done before installing (but after binary unpacking)

**Comment by ArsenShnurkov** [comment]
it would be nice to implement egacinstall 
as in <a href="https://github.com/ArsenShnurkov/dotnet/blob/c9862e5db599dc0c24e0eb00409fb373e7bb202c/dev-dotnet/remotion-linq-eagerfetching/remotion-linq-eagerfetching-2.1.0.ebuild#L71-L93">this ebuild</a>, 
but with array

declare -a array=("one" "two" "three")

# get length of an array
local arraylength=${#array[@]}

# use for loop to read all values and indexes
local i
for (( i=0; i<${arraylength}; i++ ));
do
  echo $i+1 " / " ${arraylength} " : " ${array[$i]}
done

**Comment by mpkh** [comment]
agreed, you can tweak dotnet eclass for that, this function is horrible in current version
