### ISSUE TITLE
Q: Is dotnet & mono dead (and microsoft with xamarin)?

### ISSUE THREAD

**Issue by ArsenShnurkov** [gentoo/dotnet#119]
The logic is following:
1) C# is good for desktop development (because of XAML)
2) XAML is not available on linux (Xamarin.Forms is under license from $299)
3) Microsoft abadoned WPF and Silverlight, Xamarin abadoned Moonlight
4) Microsoft is advising to use HTML5 and javascript
=> There is no sense to use C# (requires more skills and longer learning path than to use node.js)

JavaScript is assembly language of the web (c)
=> soon compilers for it will arrive for all possible languages (like https://github.com/sq/JSIL, https://github.com/bridgedotnet/Bridge, https://github.com/Microsoft/TypeScript)

Yes, for now you can code something, but will that stay after year 2023? (end of life for WPF)
Visual Studio is using XAML, but XAML rendering engine is using C++ and COM,
they can rewrite it to use javascript or something else (~4-8 times till year 23).
So I see no reasons to use C# in the long run.

Of course, such a large company can't fail, and so on.
But what will distinguish it from the developer's point of view:
- from IBM with Eclipse/Java ?
- from Google with Chromium OS (gentoo based), and Go language ?
- from Samsung/Mozilla with Rust and Servo engine as backend?

Everything has frameworks to generate HTML, and uses same javascript libraries...

**Comment by Heather** [comment]
Discussion about this topics will anyway be some personal opinion holy-war

In nutshell I blame any person who push JavaScript forward

COM is really dead

**Comment by ArsenShnurkov** [comment]
> In nutshell I blame any person who push JavaScript forward

why you don't argue against x86 in favor of Itanium ?
the logic is the same - former is interpreted, and later is compile-time analysed.

What I see - developers learns JS and switches to JS, and new desktop technologies (Mir, Wayland) will have a long time to be complete for linux (in terms of XAML support with GPU acceleration)

**Comment by Heather** [comment]
@ArsenShnurkov nowadays developers should know js, it's a fact, sad one. however C# or another languages are additional knowledge because at least for me development in js is just hell...

**Comment by x335** [comment]
for me ...
now, I accepted that 
1. the future presentation layer is Web Technology.
2. javascript is an assembly language of the Web


but I love C#  and associated tools (eg. IDE) too.
C# code can be convert to javascript.
so..
why abandon our beloved language?
Lets grow the C# language and tools to the way of future.
if Microsoft ignore the language,  never-mind ... we can take care of it  :)

lets prepare for the future 

I need ...

1. more C# features (like in TypeScript) and cross compile to js
    todo: 

         I will study the Roslyn's C#
         and extend it to any way I want (my dream... as if I'm a wizard)

2. supported IDE 
   todo:
           
          I will study and extend VisualStudio  or 
          other IDE ( eg. atom ide)  
 
cheers !

**Comment by x335** [comment]
@ArsenShnurkov 
        
In my opinion...

1.   XAML, 
umm... just skip it, and look forward 
      it will be replaced with Html.
      and there are XAML-similar techs,
      eg. Facebook React, Facebook Jsx
      and TypeScript 1.5  that support the Jsx.

2.   ' Everything has frameworks to generate HTML, and uses same javascript libraries... '

     javascript code can be written in countless ways
    and that effect the outcome performance. why use the same  javascript libraries.
   ( eg. http://www.infoworld.com/article/2975919/javascript/new-javascript-based-language-brings-the-speed.html)

       C, C++,Rust,Go, jited code of .net, java => go to CPU instructions and runs on the same CPU.
      but the languages exist and differentiate itself from many aspects
      eg .  language concepts, tools ,  performance,   fan clubs etc

**Comment by biergaizi** [comment]
This is a bugtracker for Gentoo dotnet overlay issues, please find a better place to wage holy wars.
