### ISSUE TITLE
Req: mono-4.2.0.207

### ISSUE THREAD

**Issue by ArsenShnurkov** [gentoo/dotnet#124]
v4.2.0.207 is  released:
https://github.com/mono/mono/releases/tag/mono-4.2.0.207

Todo list:

1) This patch should be reviewed:
https://github.com/gentoo/dotnet/blob/master/dev-lang/mono/mono-4.2.0.179.ebuild#L72-L73

2) DockPanelSuite requires a patch for Windows.Forms

3) There was bug in sgen, see https://github.com/gentoo/dotnet/issues/123
this should be retested on this version

**Comment by Heather** [comment]
https://github.com/gentoo/dotnet/commit/a4ccbda120c1251a876779b7c001a34a5230d5b2

please split TODO notes from this list into separated issues
