### ISSUE TITLE
Bug, mono: Monodevelop not starting

### ISSUE THREAD

**Issue by ArsenShnurkov** [gentoo/dotnet#126]
https://gist.github.com/ArsenShnurkov/044bb15725848a6af54a

Type 'System.Diagnostics.SystemDiagnosticsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' not found.

    # mono -V
    Mono JIT compiler version 4.0.3 (Stable 4.0.3.20/d6946b4 Mon Aug 31 03:54:02 UTC 2015)
    Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
    	TLS:           __thread
    	SIGSEGV:       altstack
    	Notifications: epoll
    	Architecture:  amd64
    	Disabled:      none
    	Misc:          softdebug 
    	LLVM:          supported, not enabled.
    	GC:            sgen

**Comment by ArsenShnurkov** [comment]
https://github.com/mono/mono/blob/8fbf7f3617b3e44d71c59580f4495c6c3b700934/mcs/class/System/System.dll.sources#L978

**Comment by ArsenShnurkov** [comment]
Showing differences between /etc/mono/4.5/machine.config and /etc/mono/4.5/._cfg0000_machine.config
    --- /etc/mono/4.5/machine.config        2015-08-31 08:04:58.661320671 +0300
    +++ /etc/mono/4.5/._cfg0000_machine.config      2015-08-31 06:56:56.000000000 +0300
    @@ -13,14 +13,11 @@
                    <section name="startup" type="System.Configuration.IgnoreSection, System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" allowLocation="false"/>
                    <section name="system.codedom" type="System.CodeDom.Compiler.CodeDomConfigurationHandler, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
                    <section name="system.data" type="System.Data.Common.DbProviderFactoriesConfigurationHandler, System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
    -               <section name="system.diagnostics" type="System.Diagnostics.SystemDiagnosticsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
    +               <section name="system.diagnostics" type="System.Diagnostics.DiagnosticsConfigurationHandler, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />

**Comment by Heather** [comment]
So mono 4.2 bug?

**Comment by ArsenShnurkov** [comment]
Not a bug. Just insufficient documentation of development process.
