### ISSUE TITLE
nuget_src_unpack - what was the idea behind this function?

### ISSUE THREAD

**Issue by ArsenShnurkov** [gentoo/dotnet#134]
https://github.com/gentoo/dotnet/blob/6d5fcbd2c4d9c41f8fcd519738ebf014a279f875/eclass/nuget.eclass#L60-L73

because, If ebuild doesn't override src_unpack, this code tries to instal the package being built. This is very strange for gentoo, which should be built from sources. And I don't know any standard for distributing sources with nuget. Where I can read one?

Blame - https://github.com/gentoo/dotnet/blame/6d5fcbd2c4d9c41f8fcd519738ebf014a279f875/eclass/nuget.eclass#L72
points to @Heather 

I can imagine, that this line should install local binary of nuget into the project local directory, but in this case the name of nuget package should be hardcoded into eclass instead of using the name of compiling ebuild. And this is not very good idea, because in gentoo we have a global version of nuget, why to copy into each package?

**Comment by ArsenShnurkov** [comment]
for now, I made a workaround with code

    src_unpack()
    {
        default_src_unpack 
    }

which is documented in
https://projects.gentoo.org/pms/5/pms.html#x1-1110009.1.17

**Comment by Heather** [comment]
@ArsenShnurkov hello
my idea of `nuget` was following:

introduce `nuget` `IUSE` flag for packages that are on `nuget` to download them from nuget. (if sources fails with some reason or dependies is complicated or if user just want binaries).

or maybe even introduce few packages that just downloads and instulls from nuget, reason is obviously - easy maintaince 

Here is usage example where nuget is alternative way: https://github.com/gentoo/dotnet/blob/master/dev-dotnet/fake/fake-3.23.0.ebuild#L34

`NUGET_NO_DEPEND="1"` says that nuget is not forced being in deps

`src_compile` does nothing and `src_install` just installs sources from `nuget_src_unpack`

thank you for interesting, if you will find that it should be documented or improved - contributions are still being very welcome

**Comment by ArsenShnurkov** [comment]
why not to rename **nuget_src_unpack** to something like *nuget_get_src_from_nupkg* or any another name to not interfere with default package steps ? Because each time when one use **inherit nuget** he will be forced to override src_unpack

**Comment by Heather** [comment]
because for nuget-only ebuilds you will need only inherit eclass and write src_install logic

**Comment by ArsenShnurkov** [comment]
But in your package you didn't do that.

May be we need 2 or 3 different IUSE's ? One for sources, one for binaries? for example **nuget** for unpacking sources, and **nuspec** for build binaries and **nupkg** for installing binary nuget packages?

**Comment by Heather** [comment]
@ArsenShnurkov yes, checking nuget use flag inside nuget_src_unpack  is actually good idea but then it will be good if eclass itself will add and this useflag

**Comment by ArsenShnurkov** [comment]
Or we cah make 2 different eclasses. For example **nuget** and **nupack**.

The idea about setting this use-flag from inside of eclass is interesting.

**Comment by ArsenShnurkov** [comment]
I added the line 

    IUSE+="+myverycustomflag"

into the .eclass 

and then the line

IUSE="${IUSE/+myverycustomflag/-nothing_none_absolutely/} +net45 developer debug +gac -myverycustomflag +nupkg doc"

into my ebuild.

The use "myverycustomflag" is still enabled when i am trying to emerge ebuild.
How to disable this use from ebuild?

**Comment by Heather** [comment]
> is it possible to define the default value of IUSE-flag in the .eclass file ?

yes but it should not be enabled by default, and then nutet_src_unpack will be more complicated.. okay, adding nuget check to `nutet_src_unpack ` is not good idea since what if this ebuild works only with nuget and then there is no sense to have such use flag

**Comment by Heather** [comment]
I'm fine with 2 different eclasses
