### ISSUE TITLE
xsp problems in main tree

### ISSUE THREAD

**Issue by ArsenShnurkov** [gentoo/dotnet#135]
http://packages.gentooexperimental.org/repoman-current-issues.txt
(last 3 lines)

"www-servers/xsp-2014.12-r2014120900.ebuild: net35
www-servers/xsp-2014.12-r2014120900.ebuild: net40
www-servers/xsp-2014.12-r2014120900.ebuild: net45"

**Comment by Heather** [comment]
thanks, metadata should be updated

**Comment by Heather** [comment]
https://github.com/gentoo/gentoo/commit/e5f99201e400ad15ef01a260910449545c7c02c3 done

**Comment by ArsenShnurkov** [comment]
how this ebuild is suppoed to work, if it deosn't contain SRC_URI ?
https://github.com/gentoo/gentoo/blob/master/www-apache/mod_mono/mod_mono-2.10.ebuild

**Comment by mpkh** [comment]
@ArsenShnurkov possibly one of inherits provide it, often happens
