### ISSUE TITLE
[Req] ebuild for coreclr

### ISSUE THREAD

**Issue by ArsenShnurkov** [gentoo/dotnet#148]
it is great idea to run ASP.NET 5 on top of .NET Core (c) https://github.com/dotnet/coreclr/blob/master/Documentation/install/get-dotnetcore-dnx-linux.md

instructions for building from source - https://github.com/dotnet/coreclr/blob/master/Documentation/building/linux-instructions.md (Ubuntu 14.04 LTS is the distro the team uses)

**Comment by ArsenShnurkov** [comment]
actually i am not sure that clrcore is better that mono for hosting, because mono supports ApplicationDomain concept and coreclr doesn't.
https://social.msdn.microsoft.com/Forums/vstudio/en-US/3ad241e0-ea89-479d-a145-0a01c124c1f3/what-is-the-difference-between-process-and-application-domain-in-the-context-of-net-applications?forum=clr

**Comment by ArsenShnurkov** [comment]
v1.0 released

https://blogs.msdn.microsoft.com/dotnet/2016/06/27/announcing-net-core-1-0/

**Comment by vanthome** [comment]
any chance we get a .net core ebuild?

**Comment by ArsenShnurkov** [comment]
yes, overlay is always open for new contributors :)

**Comment by mpkh** [comment]
please check out provided ebuild
