### ISSUE TITLE
dbus-sharp

### ISSUE THREAD

**Issue by seijikun** [gentoo/dotnet#15]
There is a rather old and buggy version of [dbus-sharp](https://github.com/mono/dbus-sharp) in the gentoo repo, but wouldn't this be a better place for it?
I tried creating an ebuild for [version 0.8.1](https://github.com/mono/dbus-sharp/releases) myself but failed due to a lack of knowledge.

**Comment by genterminl** [comment]
0.8.1 is the latest release, and the latest commit is nearly a year ago, so it doesn't look like this is changing much.  0.8.1 has been in the main Gentoo tree for a while now, although it fails with the strong signing issue, but there is also a version in the overlay (should it really be -r1?) which seems to work fine.  Is this issue still relevant?

**Comment by seijikun** [comment]
No, its not relevant anymore.
