### ISSUE TITLE
Malformed CVS Header on line: 3

### ISSUE THREAD

**Issue by ArsenShnurkov** [gentoo/dotnet#155]
https://gist.githubusercontent.com/ArsenShnurkov/6302c6855b99507ae9e5/raw/3782ec91128681f723057d9d3a16eadbc5a3df34/gistfile1.txt

**Comment by Heather** [comment]
@ArsenShnurkov looks like very old portage version

**Comment by ArsenShnurkov** [comment]
sys-apps/portage-2.2.20
default for sabayon

**Comment by Heather** [comment]
@ArsenShnurkov because it's stable but not a secret that often stable things are outdated

**Comment by ArsenShnurkov** [comment]
Yes, message gone with 2.2.25 (which introduces EAPI-6), but now new messages appear (on obsoleted <code>inherit base</code> )

https://gist.githubusercontent.com/ArsenShnurkov/1d827bd42a6da9a259da/raw/10580e6aef2dbe58ffe71d70b88f8b0e18dadee9/gistfile1.txt

**Comment by Heather** [comment]
@ArsenShnurkov maybe some of those messages are true...
