### ISSUE TITLE
java contributors are more active

### ISSUE THREAD

**Issue by ArsenShnurkov** [gentoo/dotnet#159]
https://github.com/gentoo/java-overlay/graphs/contributors

Their commits should be summed up by all members (i.e. 502+427+417+352+319+313+269+122... ~= 2500..3000) because they use branching less actively

In this overlay there are 194 commits.

so, we have difference in order of magnitude (they are 10..20 times more active)

**Comment by Heather** [comment]
I can ask for help in mailing list but still... I'm even not lead of gentoo dotnet: https://wiki.gentoo.org/wiki/Project:Dotnet
Maybe I should become one... Java just historically has more crossplatfom things done

**Comment by ArsenShnurkov** [comment]
Which mailing list do you have in mind?
There is no dotnet mailing list - https://archives.gentoo.org/lists

**Comment by Heather** [comment]
I meant gentoo-dev maining list
