### ISSUE TITLE
libgdiplus-4.2 and 4.2-r1 are not installable because of no 'QuantizeBuffer'

### ISSUE THREAD

**Issue by ArsenShnurkov** [gentoo/dotnet#173]
https://gist.github.com/bce2f3c0d86c6047feb7

../src/.libs/libgdiplus.so: undefined reference to `QuantizeBuffer'
collect2: error: ld returned 1 exit status

media-libs/giflib-4.2.3-r1
(ebuilds 3.12, 4.2-* all contain line <code>\>=media-libs/giflib-4.2.3</code>)

QuantizeBuffer has been removed since giflib 4.2.0

**Comment by ArsenShnurkov** [comment]
see also
https://github.com/rainycape/magick/issues/21

**Comment by ArsenShnurkov** [comment]
<a href="https://github.com/gentoo/dotnet/blob/master/dev-dotnet/libgdiplus/libgdiplus-4.2-r1.ebuild">dev-dotnet/libgdiplus-4.2-r1</a>

**Comment by ArsenShnurkov** [comment]
3.12 applies this patch:
https://github.com/gentoo/dotnet/blob/master/dev-dotnet/libgdiplus/libgdiplus-3.12.ebuild#L42

**Comment by Heather** [comment]
@ArsenShnurkov I see - will you try to PR into mainstream?

**Comment by ArsenShnurkov** [comment]
@Heather That's uneasy question. The authors of <code>giflib</code> had some reasons to remove this code. Who am I to go against their will ?

**Comment by Heather** [comment]
merged
