### ISSUE TITLE
Unable to compile Sqlite code in csharp

### ISSUE THREAD

**Issue by logicalguy** [gentoo/dotnet#18]
How do I include support for Sqlite libraries?  When I type
* using Mono.Data.Sqlite

It says I am missing an assembly reference.

What am I missing? 
I have dev-lang/mono-3.8.0 (~amd64) and dev-lang/sqlite-3.8.6 installed in my system.

Thanks.

**Comment by ArsenShnurkov** [comment]
please give a direct link to the git repository of your project (to project file).
There should be a reference to System.Data.dll
(and with latest mono, in build options the runtime should be set to 4.5)
