### ISSUE TITLE
Xamarin is acquired by Microsoft

### ISSUE THREAD

**Issue by ArsenShnurkov** [gentoo/dotnet#180]
http://blogs.microsoft.com/blog/2016/02/24/microsoft-to-acquire-xamarin-and-empower-more-developers-to-build-apps-on-any-device/
"UWP will be adapted to cover iOS and Android as well as Windows" (speculations)

https://blog.xamarin.com/a-xamarin-microsoft-future/
"mission to make native mobile development fast, easy, and fun"
350 people around the world

$400m to $500m deal 

I am not sure yet is it a problem or not, but libreoffice, mariadb, and many other opensource projects was forked after similar corporate acquisitions.

**Comment by Heather** [comment]
@ArsenShnurkov so how do you plan to resolve this issue?

**Comment by ArsenShnurkov** [comment]
@Heather - This event probably may change my plans ( Should I switch to studying https://github.com/froggey/Mezzano instead of https://github.com/mosa/MOSA-Project ? )

github is the only channel which I can use communicate about this topic. You probably will not use general gentoo forum for that, there is no mailing list, there is no special forum about CLI/C# on portage/paludis based system. Where this should be put to get responses?

You didn't answered to my question about mailing list - https://github.com/gentoo/dotnet/issues/159#issuecomment-186819980

**Comment by Heather** [comment]
I'd suggest https://github.com/stepcut/idrOS
