### ISSUE TITLE
Monodevelop fails with USE_DOTNET="net45"

### ISSUE THREAD

**Issue by PeeJay** [gentoo/dotnet#192]
Having the line USE_DOTNET="net45" in make.conf results in the following error:

 * ERROR: dev-util/monodevelop-6.0.0.4761::dotnet failed (setup phase):
 *   USE Flag 'net45' not in IUSE for dev-util/monodevelop-6.0.0.4761

**Comment by Heather** [comment]
@PeeJay I've got `DOTNET_TARGETS="net45 net40"` in `make.conf` however still maybe this behaviour should be corrected

**Comment by PeeJay** [comment]
Aah, I take it I should be using DOTNET_TARGETS rather than USE_DOTNET then? That fixes the problem. Is there any documentation on this anywhere? I couldn't find any.

**Comment by Heather** [comment]
@PeeJay no :( I didn't write any so far

**Comment by Heather** [comment]
cuurently just added to readme https://github.com/gentoo/dotnet/commit/225706f0a197fefad1f2ea1a606d1571234d4d18

**Comment by genterminl** [comment]
I have DOTNET_TARGETS="net45 net46 net52" but am still getting errors of "User did not set any netNN use-flags in make.conf or profile, .ebuild demands USE_DOTNET=net45"  Any idea what I'm missing?

**Comment by mpkh** [comment]
@genterminl I failed to build xdt which needs for nuget so first I need to resolve those problems, "User did not set any net..." is harmless message (should be), it's not error (and possibly on ebuild side)
you can check there how eclass works there https://github.com/gentoo/dotnet/blob/master/eclass/dotnet.eclass

**Comment by genterminl** [comment]
@mpkh thanks.  putting USE+="net45" before the emerge command silenced that warning.  I'm still getting errors about installing a delayed signed target, but that's not for this issue. (and I'm not at my main PC right now to even check details.) and it's for several different ebuilds.

**Comment by genterminl** [comment]
@mpkh I got xdt-for-monodevelop to emerge.  I'll post comment in issue 305.
