### ISSUE TITLE
mono circular dependency

### ISSUE THREAD

**Issue by ArsenShnurkov** [gentoo/dotnet#198]
i didn't dig that, but it prevents from building Unity in Sabayon:

http://scrinfra.sabayonlinux.org/logs/2016-06-27/unity.1466997488.log
- Error: circular dependencies:

(dev-lang/mono-4.4.0.148:0/0::gentoo, ebuild scheduled for merge) depends on
 (dev-dotnet/libgdiplus-4.2-r2:0/0::gentoo, ebuild scheduled for merge) (buildtime)
  (dev-lang/mono-4.4.0.148:0/0::gentoo, ebuild scheduled for merge) (buildtime)

**Comment by Cynede** [comment]
@ArsenShnurkov yes, current way is a bit weird
```
USE="minimal" emerge mono
emerge mono
```
