### ISSUE TITLE
dotnet-cli fails

### ISSUE THREAD

**Issue by sergot** [gentoo/dotnet#212]
just noticed this:

```
[ 78%] Linking CXX shared library System.Native.so
$<TARGET_FILE:System.Native>.dbg
[ 78%] Built target System.Native
[ 80%] Linking CXX static library System.Native.a
[ 80%] Built target System.Native-Static
make: *** [Makefile:128: all] Error 2
Failed to build corefx native components.
 * ERROR: dev-dotnet/dotnet-cli-1.0.0_pre2_p003121::dotnet failed (compile phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line 115:  Called src_compile
 *   environment, line 357:  Called die
 * The specific snippet of code:
 *       ./build.sh native x64 release || die
 * 
 * If you need support, post the output of `emerge --info '=dev-dotnet/dotnet-cli-1.0.0_pre2_p003121::dotnet'`,
 * the complete build log and the output of `emerge -pqv '=dev-dotnet/dotnet-cli-1.0.0_pre2_p003121::dotnet'`.
 * The complete build log is located at '/tmp/portage/dev-dotnet/dotnet-cli-1.0.0_pre2_p003121/temp/build.log'.
 * The ebuild environment file is located at '/tmp/portage/dev-dotnet/dotnet-cli-1.0.0_pre2_p003121/temp/environment'.
 * Working directory: '/tmp/portage/dev-dotnet/dotnet-cli-1.0.0_pre2_p003121/work/corefx-1.0.0'
 * S: '/tmp/portage/dev-dotnet/dotnet-cli-1.0.0_pre2_p003121/work'

>>> Failed to emerge dev-dotnet/dotnet-cli-1.0.0_pre2_p003121, Log file:

>>>  '/tmp/portage/dev-dotnet/dotnet-cli-1.0.0_pre2_p003121/temp/build.log'
```

is this known? how can I handle this?

**Comment by mpkh** [comment]
though we should mask this ebuild for a while, it was contributed as is

**Comment by sergot** [comment]
Is there any way to install it without this ebuild? Didn't find any "tutorial". :(

**Comment by mpkh** [comment]
@sarnold ideally by fixing this ebuild I guess otherwise manually but I can't tell much, never used it

**Comment by ArsenShnurkov** [comment]
@sergot - please paste a full build log too

**Comment by vanthome** [comment]
for me it compiles just fine. I'm running all latest stuff on my Gentoo box

**Comment by ArsenShnurkov** [comment]
for me too. But I was learned to **listen** users, they not lie in most of cases.

**Comment by mpkh** [comment]
@sarnold nearly some depending package were added to dotnet cli so please retest and reopen it if it's still fails, provide mono version

**Comment by sergot** [comment]
hey, looks like it still fails, here is the full log:

https://paste.pound-python.org/show/ZFmFTcVCcPT6HolUyN7i/

@vanthome @ArsenShnurkov

**Comment by sergot** [comment]
Looks like the solution was:

`dev-libs/openssl -bindist
net-misc/openssh -bindist 
dev-qt/qtnetwork -bindist`

works like a charm now :)

**Comment by mpkh** [comment]
maybe ebuild should be corrected then
