### ISSUE TITLE
dev-util/nant[nupkg] should depend on nuget

### ISSUE THREAD

**Issue by lorem-ipsum** [gentoo/dotnet#213]
dev-util/nant-0.93.5019_p201511150 builds fine but fails in the end with
`/var/tmp/paludis/dev-util-nant-0.93.5019_p201511150-r0/temp/loadsaveenv:` line 2045: nuget: command not found`
Installing nuget manually fixes the issue, looks like there is a build dependency missing.

**Comment by mpkh** [comment]
@lorem-ipsum it's called runtime dependency,  you can make PR with adding nuget as RDEPEND

**Comment by lorem-ipsum** [comment]
If it fails during build I would call it a build dependency, not a runtime dependency. Assuming that it is a runtime dependency as well I added it for both. See PR #215
