### ISSUE TITLE
dev-dotnet/dotnet-cli

### ISSUE THREAD

**Issue by ArsenShnurkov** [gentoo/dotnet#216]
<pre>CMake Error at System.Net.Security.Native/CMakeLists.txt:22 (message):
  Cannot find libgssapi_krb5 and System.Net.Security.Native cannot build
  without it.  Try installing libkrb5-dev (or the appropriate package for
  your platform)</pre>

https://gist.github.com/d2f8c48ba61b2840129eedbd187cd81c

**Comment by mpkh** [comment]
should be call for @bsagal

**Comment by bsagal** [comment]
does installing `app-crypt/mit-krb5` solve the problem, if so i will update the dependencies
