### ISSUE TITLE
gtk-sharp fails to build`

### ISSUE THREAD

**Issue by mpkh** [gentoo/dotnet#222]
```
 * QA Notice: 'libtoolize' called by src_prepare: dev-dotnet/gtk-sharp-2.12.21-r1
 * Use autotools.eclass instead of calling 'libtoolize' directly.
libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.in,
libtoolize: and rerunning libtoolize and aclocal.
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
 * ERROR: dev-dotnet/gtk-sharp-2.12.21-r1::dotnet failed (prepare phase):
 *   eapply_user (or default) must be called in src_prepare()!

```

**Comment by mpkh** [comment]
@ArsenShnurkov be more careful when change `EAPI`

**Comment by mpkh** [comment]
I've fixed that package https://github.com/gentoo/dotnet/commit/9824f403c61c079546256a90402c272becf1ddd3 but not sure if there are more breakage, please review, and not sure about libtoolize warning

**Comment by mpkh** [comment]
for example check if there is no same problem there https://github.com/gentoo/dotnet/commit/079be061a08c312d038cb8def5c2f2beb8f86e5f and for other packages.

**Comment by piedar** [comment]
Also

    * ERROR: dev-dotnet/xdt-for-monodevelop-2.8.1::dotnet failed (prepare phase):
    *   eapply_user (or default) must be called in src_prepare()!
