### ISSUE TITLE
nuget EAPI=6 require eapply_user in src_prepare

### ISSUE THREAD

**Issue by Krnlsoft** [gentoo/dotnet#227]
Please fix the nuget ebuilds
it's required eapply_user in src_prepare 

Thank you.

**Comment by mpkh** [comment]
@krifisk I wonder if it's still broken, `default` there should be fine https://github.com/gentoo/dotnet/blob/master/dev-dotnet/nuget/nuget-2.8.7-r2.ebuild#L45 /cc @ArsenShnurkov

**Comment by mpkh** [comment]
@krifisk I've re-tested `nuget-2.8.7-r2` and it works for me - please make sure you've got overlay up to date, there was such issue but it was fixed

**Comment by Krnlsoft** [comment]
Yeah sorry, it's fixed on r2 I was emerging nuget-2.8.7 (since r2 was not accepted ~amd64)

What's the reason of keeping packages that do not work?
I would remove nuget-2.8.7 nuget-2.8.7-r1

Thank you.

**Comment by mpkh** [comment]
@Krnlsoft yes, old versions should be removed

**Comment by Krnlsoft** [comment]
Thank you than, close the issue.

Have a nice day.

**Comment by mpkh** [comment]
no problem! note that it's experimental unstable community driven overlay and any help will be very welcome :)
