### ISSUE TITLE
=media-sound/banshee-2.6.1-r1 causing repman failure

### ISSUE THREAD

**Issue by bsagal** [gentoo/dotnet#232]
`=media-sound/banshee-2.6.1-r1` is causing a repman failure as it depends on net-libs/libsoup-gnome which is masked. The main tree includes `=media-sound/banshee-2.6.2-r1`.

Is there a reason to keep banshee around in the dotnet tree if there is a later version in the main tree?

**Comment by mpkh** [comment]
No, it could be dropped already
