### ISSUE TITLE
Upgrade dotnet-cli to 1.0.1

### ISSUE THREAD

**Issue by vanthome** [gentoo/dotnet#242]
https://blogs.msdn.microsoft.com/dotnet/2016/09/13/announcing-september-2016-updates-for-net-core-1-0/

**Comment by bsagal** [comment]
There is no new version of the the CLI (just a new build).

The new version is for the included .NET core framework and I need the work out the equivalent versions of coreclr and corefx.

**Comment by gsnerf** [comment]
I ran into the problem of wanting to use 1.0.1 too just a few moments ago :)
Perhaps it would make sense to split ebuilds for framework and cli tools?

**Comment by bsagal** [comment]
I am looking into splitting up based on the ubuntu debs

**Comment by gsnerf** [comment]
The new CoreCLR version seems to be https://github.com/dotnet/coreclr/releases/tag/v1.0.4

**Comment by bsagal** [comment]
@gsnerf 
Thank You
What happens if your project file depends on a newer dotnet than the cli is using?

**Comment by gsnerf** [comment]
It states, that the project depends on framework 1.0.1 but only 1.0.0 is installed and suggests to add the new framework.

**Comment by vanthome** [comment]
@gsnerf yes that's what happens in my case as well. And yes, the CLI is still on preview2 but it seems like you can have multiple runtime versions installed and use them with the preview2 CLI.

**Comment by vanthome** [comment]
Meanwhile there is 1.1.1 out. Any chance that this gets version bumped soon?

**Comment by mpkh** [comment]
@vanthome just try to bump by yourself, be sure that you tested in before pull request :+1:

**Comment by vanthome** [comment]
Would love to do so but never hacked on eBuild so far. I guess I have to just edit the local eBuild end build it again... is that the process?

**Comment by mpkh** [comment]
@vanthome there is https://devmanual.gentoo.org and ​#gentoo-dev-help channel on IRC, you need to make ebuild copy, run ebuild .... digest there (man ebuild) and test it, make repository fork, add it to git remotes, create separate branch of repository, git add it there, commit, push, open pull request :)
