### ISSUE TITLE
dev-lang/fsharp build fails

### ISSUE THREAD

**Issue by piedar** [gentoo/dotnet#255]
# emerge -v dev-lang/fsharp

...

    Build FAILED.
    Errors:

    /var/tmp/portage/dev-lang/fsharp-4.0.1.1/work/fsharp-4.0.1.1/src/fsharp/FSharp.Core/FSharp.Core.fsproj (default targets) ->
    /var/tmp/portage/dev-lang/fsharp-4.0.1.1/work/fsharp-4.0.1.1/lib/bootstrap/4.0/Microsoft.FSharp.Targets (CoreCompile target) ->

        FSC: error FS0215: Multiple references to 'mscorlib.dll' are not permitted
        FSC: error FS0215: Multiple references to 'mscorlib.dll' are not permitted

         0 Warning(s)
         2 Error(s)

**Comment by mpkh** [comment]
@piedar I'll take a look

**Comment by mpkh** [comment]
@piedar bumped to 4.0.1.13

**Comment by mpkh** [comment]
builds fine for me, please re-open in case if it's still failing for you

**Comment by piedar** [comment]
Perfect, thanks!  Latest Monodevelop depends on it.

**Comment by mpkh** [comment]
@piedar really? that's strange... but it's not in dependencies list, right?

**Comment by piedar** [comment]
Not the current version in the tree.  I'm trying to get v6.1.1.15 to build from the Github tarball without bundled dependencies.  It's slow going.

**Comment by mpkh** [comment]
@piedar I see, ideally would be great to have ebuild for it in future :)
