### ISSUE TITLE
Wrong DIST checksums in Manifest for mono-options

### ISSUE THREAD

**Issue by programmador** [gentoo/dotnet#288]
mono-options is not installable without a hacking. It claims that downloaded `mono-4.5.2_p2016061606.tar.bz2` has wrong size (and also checksums).
I've downloaded that file few times manually using wget and a browser - it looks like it really has changed.

I've copied the ebuild folder to my local repo /usr/local/portage (and also eclasses), deleted a Manifest file and installed a package this way:
`ebuild mono-options-4.4.0.0.ebuild manifest clean merge`
It was installed successfully.

Then I've cloned the dotnet repo to make a fix and a pull request and noticed that my manifest has much more data: AUX, DIST, EBUILD, MISC. And the original Manifest has only DIST. I've compared original folder with mine using meld and decided "Ok, I'll make strictly like in original" and removed AUX, EBUILD and MISC, leaving only DIST in my Manifest.

This made my ebuild non-installable.
Here's `emerge` output:
```
>>> Verifying ebuild manifests
!!! A file is not listed in the Manifest: '/usr/local/portage/dev-dotnet/mono-options/mono-options-4.4.0.0.ebuild'
```
and here's `ebuild` output:
`Missing digest for '/usr/local/portage/dev-dotnet/mono-options/mono-options-4.4.0.0.ebuild'`

So what should I do? As I understand, pushing a new Manifest with AUX, EBUILD and MISC is a wrong way? Then how can I check that my ebuild is installable/usable with "cut" Manifest (with only DIST present)?

**Comment by mpkh** [comment]
@programmador may you contribute the correction?

**Comment by programmador** [comment]
https://github.com/gentoo/dotnet/pull/289
