### ISSUE TITLE
checking for gmcs... no

### ISSUE THREAD

**Issue by ArsenShnurkov** [gentoo/dotnet#29]
checking for MONO_MODULE... yes
checking for gmcs... no
configure: error: You need to install 'gmcs'

!!! Please attach the following file when seeking support:
!!! /var/calculate/tmp/portage/dev-dotnet/xsp-2014.11/work/xsp-2014.11_build/config.log

    # emerge -pv mono && dmcs --version

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild   R   *] dev-lang/mono-9999::dotnet  USE="-doc -minimal -pax_kernel -xen" 0 KiB

Total: 1 package (1 reinstall), Size of downloads: 0 KiB
Mono C# compiler version 3.99.0.0

**Comment by ArsenShnurkov** [comment]
temporary solved by ading

    CCS=/usr/bin/mcs
    GMCS=/usr/bin/dmcs

to make.conf

**Comment by Heather** [comment]
@ArsenShnurkov I think it's possible to add it even to ebuild

**Comment by ArsenShnurkov** [comment]
not the single ebuild is affected, so it is better to understood the problem to it's roots

**Comment by ArsenShnurkov** [comment]
works for me

**Comment by jhuebner79** [comment]
media-gfx/paint-mono-0.1.63 also fails because of `/bin/sh: gmcs: command not found`
