### ISSUE TITLE
error in msbuildtasks ebuild 1.5.0.196

### ISSUE THREAD

**Issue by borysn** [gentoo/dotnet#292]
hey guys,

msbuildtasks-1.5.0.196.ebuild contains an error, the directory for `MSBuild.Community.Tasks.dll` is not correct, it is found within `../obj/..` and not `../bin/..`

```
--- msbuildtasks-1.5.0.196.ebuild	2017-04-27 10:16:45.702591093 -0500
+++ msbuildtasks-1.5.0.196.ebuild.new	2017-04-27 10:10:03.023625273 -0500
@@ -44,7 +44,7 @@
 	else
 		DIR="Release"
 	fi
-	egacinstall "Source/MSBuild.Community.Tasks/bin/${DIR}/MSBuild.Community.Tasks.dll"
+	egacinstall "Source/MSBuild.Community.Tasks/obj/${DIR}/MSBuild.Community.Tasks.dll"
 	einstall_pc_file "${PN}" "${PV}" "MSBuild.Community.Tasks"
 	insinto "/usr/lib/mono/4.5"
 	doins "Source/MSBuild.Community.Tasks/MSBuild.Community.Tasks.Targets"
```

cheers!

**Comment by ArsenShnurkov** [comment]
Why it's in obj instead of bin? may be <a href="https://github.com/loresoft/msbuildtasks/blob/master/Source/MSBuild.Community.Tasks/MSBuild.Community.Tasks.csproj#L34">.csproj</a> should be patched instead...

**Comment by borysn** [comment]
@ArsenShnurkov I am not sure, it was just what I found, and the first solution I thought of. I am impartial to what gets updated.
