### ISSUE TITLE
Ebuild naming and package naming

### ISSUE THREAD

**Issue by ArsenShnurkov** [gentoo/dotnet#359]
Right now ebuild names are in lower case (to match names of github repositories). But in nuget.org names follows camel case similary to C# namespace names.

for example:
dev-donet/mono-addins
and
<a href="https://www.nuget.org/packages/Mono.Addins/">Mono.Addins</a>

what do you think about naming ebuilds like
dev-dotnet/Mono.Addins ?

Gentoo manual recommends lowercase:
https://devmanual.gentoo.org/ebuild-writing/file-format/index.html
  
> The name section should contain only lowercase non-accented letters, the digits 0-9, hyphens, underscores and plus characters. Uppercase characters are strongly discouraged, but technically valid.

**Comment by mpkh** [comment]
yes, lowercase is recommended and sure no dots
