### ISSUE TITLE
function "Exbuild" is missing from dotnet/eclass/dotnet.eclass

### ISSUE THREAD

**Issue by dallenwilson** [gentoo/dotnet#376]
I added the dotnet overlay using layman, and attempted to emerge monodevelop. One of the first dependencies pulled in was dev-dotnet/xdt-for-monodevelop-2.8.1-r2, which failed due to the 'exbuild' function being missing. Some help from the gentoo forums showed me that this function is present in the stock gentoo dotnet.eclass file, but missing (along with several others) from the dotnet overlay's version of the file.

If I'm missing something obvious in regards to installing monodevelop, please let me know. Otherwise, this looks like a bug or oversight to me.

**Comment by ArsenShnurkov** [comment]
add the line
inherit xbuild
int affected ebuild

**Comment by dallenwilson** [comment]
It's not my ebuild, but sure I can start customizing. If it works, did you want a pull request?

**Comment by ArsenShnurkov** [comment]
yes, PR will be good, thank in advance

**Comment by dallenwilson** [comment]
Yeah, adding inherit xbuild fixed it. I'll send a pull request tomorrow maybe, got sidetracked by monodevelop trying to pull in xsp-2014.12 which fails to build, instead of xsp-4 which is in the overlay and does build. I'll send both PR's when I figure it out.
