### ISSUE TITLE
Cannot open assembly '/usr/local/lib/monodevelop/bin/MonoDevelop.exe'

### ISSUE THREAD

**Issue by ArsenShnurkov** [gentoo/dotnet#38]
# LANG=C monodevelop
    Cannot open assembly '/usr/local/lib/monodevelop/bin/MonoDevelop.exe': No such file or directory.
    # which monodevelop
    /usr/local/bin/monodevelop
    # grep "EXE_PATH" /usr/local/bin/monodevelop
    EXE_PATH="${0%%/bin/monodevelop}/lib/monodevelop/bin/MonoDevelop.exe"
    	$MONO_EXEC $MONO_OPTIONS "$EXE_PATH" $* 2>&1 | tee "$_MD_REDIRECT_LOG"
    	$MONO_EXEC $MONO_OPTIONS "$EXE_PATH" $*

here the expression ${0%%/bin/monodevelop} is wrong. I don't know why it is wrong and how to fix.

/usr/local/bin is symlinked to /usr/bin
and in the PATH /usr/local/bin is placed before /usr/bin

I propose to generate exact name instead of bash expression during install of ebuild.

**Comment by Heather** [comment]
first monodevelop build issues should be somehow resolved...

**Comment by ArsenShnurkov** [comment]
the default src_configure calls econf, which passes --prefix=${EPREFIX}/usr
monodevelop ends up in /usr/lib/monodevelop/*
so in ebuild we can just replace this construction "${0%%/bin/monodevelop}" into "${EPREFIX}/usr"

**Comment by ArsenShnurkov** [comment]
src_configure() {
            ...
            # fix of https://github.com/gentoo/dotnet/issues/38
            sed -i -E -e 's#(EXE_PATH=")(.*)(/lib/monodevelop/bin/MonoDevelop.exe")#\1'${EPREFIX}'/usr\3#g' "${S}/monodevelop" || die
    }

**Comment by ArsenShnurkov** [comment]
works for me
