### ISSUE TITLE
Error message from emerge

### ISSUE THREAD

**Issue by dmcbride** [gentoo/dotnet#412]
All the portage commands are giving me this:

```
!!! Repository 'dotnet' has sync-uri attribute, but is missing sync-type attribute
```

I'm not sure where it's coming from.

**Comment by cnd** [comment]
not sure really, are you using layman? try running `layman-updater -R`

**Comment by atomsymbol** [comment]
`layman-updater -R` solved the issue for me.

**Comment by dmcbride** [comment]
I'm not sure why I didn't see the email for this, but anyway, yes, that solved it. Thanks!
