### ISSUE TITLE
dev-dotnet/dotnetcore-sdk-bin: Ability to install multiple major .NET Core versions

### ISSUE THREAD

**Issue by ngg** [gentoo/dotnet#433]
Hi!

Using the current ebuilds, it is not possible to install .NET Core SDK 2.1 and 2.2 side by side,
which can be really useful when dealing with multiple projects or when migrating one.

I have a working solution for this in our overlay at https://github.com/tresorit/tresorit-gentoo-overlay/tree/master/dev-dotnet. It contains the latest versions (`2.1.802`, `2.2.402`, `3.0.100`). This solution is modeled after `sys-devel/llvm` and `sys-devel/llvm-common`.

Are you interested in supporting this use-case?
I'd be happy to create a PR if you like the proposal.

**Comment by dargonforce** [comment]
I hope this gets a little more attention, I would love to see that

**Comment by filmor** [comment]
@ngg Just create a PR, a slotted build makes a lot of sense for this.
