### ISSUE TITLE
dev-dotnet/dotnetcore-sdk-bin-3.1.101 missing dotnet binary

### ISSUE THREAD

**Issue by askovpen** [gentoo/dotnet#463]
subj

**Comment by ngg** [comment]
Hi! Author of the last few ebuilds here. It's working for us, can you please explain what goes wrong for you?
`dev-dotnet/dotnetcore-sdk-bin` depends on `dev-dotnet/dotnetcore-sdk-bin-common` which installs the dotnet binary to `/opt/dotnet_core/dotnet` and symlinks it to `/usr/bin/dotnet`
