### ISSUE TITLE
pwsh 7.02

### ISSUE THREAD

**Issue by necrose99** [gentoo/dotnet#475]
pentoo has bumped version , **src_prepare**
### **takes a bit of neutering with arm/arm64.
https://github.com/pentoo/pentoo-overlay/issues/651
however with **src_prepare** cleaved it will 

ebuild pwsh-bin-7.0.2.ebuild package just fine.. 

IF amd64 , then src_prepare() { **else NO!!!**  might be a fix ...

_Call it lessons learned._ / feedback. 

_```
src_prepare() {
	default
	rm libcrypto.so.1.0.0 libssl.so.1.0.0 || die
}
```_

```
SRC_URI="
	amd64? ( https://github.com/PowerShell/PowerShell/releases/download/v${PV}/powershell-${PV}-linux-x64.tar.gz )
	arm?   ( https://github.com/PowerShell/PowerShell/releases/download/v${PV}/powershell-${PV}-linux-arm32.tar.gz )
	arm64? ( https://github.com/PowerShell/PowerShell/releases/download/v${PV}/powershell-${PV}-linux-arm64.tar.gz )
"
```


### arm64 Hack   KILL it with fire , and Voiol`a build/installs. 
#src_prepare() {
#	default
#	rm libcrypto.so.1.0.0 libssl.so.1.0.0 || die
#}
```_

**Comment by ngg** [comment]
`app-shells/pwsh-bin` is not currently maintained actively, but there is another way to install it if it's ok for you.
First, install `dev-dotnet/dotnetcore-sdk-bin` then run `dotnet tool install --global PowerShell` which will always install the latest version of PowerShell.

**Comment by necrose99** [comment]
pentoo has it at present https://github.com/pentoo/pentoo-overlay/tree/master/app-shells/pwsh-bin
with mods to older ebuild and bumped. paity if you will or wont .
