### ISSUE TITLE
Package for mono-4.0.0 branch

### ISSUE THREAD

**Issue by ArsenShnurkov** [gentoo/dotnet#49]
This thread is the place where to disscuss how it should be done

GitExtensions works on 3.99 (master), but crashes on 3.12. And it is good to prepare for release.

**Comment by Heather** [comment]
4 beta is released in mono-project sources, we can try to get it here

**Comment by alistair** [comment]
im assuming its going to break most packages in the gentoo repo as they won't be running .net 4.5
