### ISSUE TITLE
dev-lang/mono-9999 autotools-utils.eclass could not be found by inherit()

### ISSUE THREAD

**Issue by ethannij** [gentoo/dotnet#494]
http://dpaste.com/DFHXL9J9P emerge --info
when doing a @world update i get the message
* ERROR: dev-lang/mono-9999::dotnet failed (depend phase):
 *   autotools-utils.eclass could not be found by inherit()
despite not having mono installed. I figure this is probably a pretty simple fix seeing that it's not finding autotools-utils.eclass, but maybe it's not, just figured id put in a bug report.

**Comment by Meister1593** [comment]
+ , annoying thing in output
