### ISSUE TITLE
app-editors/visual-studio-code is obsolete

### ISSUE THREAD

**Issue by ngg** [gentoo/dotnet#504]
Upstream Gentoo has included Visual Studio Code as `app-editors/vscode` in https://github.com/gentoo/gentoo/pull/20710 and also VSCodium as `app-editors/vscodium` in https://github.com/gentoo/gentoo/pull/21045.

This makes the `app-editors/visual-studio-code` in this overlay unnecessary. It also conflicts with the official `vscode` package because both uses the `/usr/bin/vscode` file.

@kuzetsa @cnd What do you think about this? Can I simply remove the package? Or should we have a news item or maybe mark it as a "moved" package? Maybe remove the `KEYWORDS` first and remove it only later?

**Comment by cnd** [comment]
sure remove it, this overlay needs heavy cleaning

**Comment by cyborgyn** [comment]
Agree, both of it is just binary install, and the one in gentoo rep seems to be more advanced with ARM also able to install.
I am just wondering: building from source would be that hard? Shouldn't it be `app-editor/vscode-bin` instead (juts to follow naming convention)?
