### ISSUE TITLE
dev-lang/mono-3.12.1 fails to emerge

### ISSUE THREAD

**Issue by zetok** [gentoo/dotnet#53]
``build.log`` & ``emerge --info`` → https://gist.github.com/zetok/9c66288aa953f25cb2f0

**Comment by Heather** [comment]
@zetok weak, try to emerge it with `minimal` use flag

**Comment by zetok** [comment]
USE="minimal" mono-3.12.1 still fails: https://gist.github.com/zetok/97e0d006ca96b2a8577e

**Comment by Heather** [comment]
`cannot stat './../../class/lib/net_2_0//mscorlib.dll.so` hm.... weird, why it's not there...

**Comment by Heather** [comment]
@zetok seems like we should use `j1` there, try it

**Comment by zetok** [comment]
``MAKEOPTS="-j1" USE="${USE} minimal" emerge -avt1 dev-lang/mono-3.12.1-r1`` worked

**Comment by Heather** [comment]
@zetok good, I will need to add this to 3.x ebuilds also
