### ISSUE TITLE
Is bug with LDFLAGS gone for mono

### ISSUE THREAD

**Issue by Heather** [gentoo/dotnet#54]
e.g. there is :
https://github.com/gentoo/dotnet/blob/master/dev-lang/mono/mono-3.12.1.ebuild#L126

``` shell
	# Remove files not respecting LDFLAGS and that we are not supposed to provide, see Fedora
	# mono.spec and http://www.mail-archive.com/mono-devel-list@lists.ximian.com/msg24870.html
	# for reference.
	rm -f "${ED}"/usr/lib/mono/{2.0,4.5}/mscorlib.dll.so || die
	rm -f "${ED}"/usr/lib/mono/{2.0,4.5}/mcs.exe.so || die
```

however we may need those

**Comment by alistair** [comment]
ive never understood that.   from my understanding those files are 

    --aot, --aot[=options]
              This  option  is  used to precompile the CIL code in the specified assembly to native code.  The generated code is stored in a file with
              the extension .so.  This file will be automatically picked up by the runtime when the assembly is executed. 

meant to be there

**Comment by Heather** [comment]
@alistair can we safely remove those lines?

**Comment by alistair** [comment]
I think we need a way to be able to tell other apps that these are 'special'.   Sorry its been a while and its really late so I can't think what that is...

But i thought there was a exclude type support in gentoo.

**Comment by alistair** [comment]
a revdep-rebuild directory mask would probably do it.
