### ISSUE TITLE
gtk-sharp-2.99.1  SHA256 verification fails

### ISSUE THREAD

**Issue by andy-graprof** [gentoo/dotnet#61]
`build.log` and `emerge --info`: http://pastebin.com/TXwHxLS0

**Comment by Heather** [comment]
@andy-graprof very strange, because `digest` changed nothing for me and seems like it's correct for me

**Comment by andy-graprof** [comment]
manual download and sha256 also gives the wrong checksum

    a0b5f4d444f720f4d1ccb4809276c03e4ed35adde11a180680a53d2c46b62460

vs. the hash from the manifest:

    5b7c24ecd67a0af8a08143298f3d8a73a36a4a0025304d84fa23dea829f49385


    gentoo-maniac ~ # wget https://github.com/mono/gtk-sharp/archive/2.99.1.zip
    --2015-05-29 10:02:12--  https://github.com/mono/gtk-sharp/archive/2.99.1.zip
    Resolving github.com... 192.30.252.129
    Connecting to github.com|192.30.252.129|:443... connected.
    HTTP request sent, awaiting response... 302 Found
    Location: https://codeload.github.com/mono/gtk-sharp/zip/2.99.1 [following]
    --2015-05-29 10:02:13--  https://codeload.github.com/mono/gtk-sharp/zip/2.99.1
    Resolving codeload.github.com... 192.30.252.146
    Connecting to codeload.github.com|192.30.252.146|:443... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 4108685 (3.9M) [application/zip]
    Saving to: ‘2.99.1.zip’

    2.99.1.zip                 100%[========================================>]   3.92M  1.12MB/s   in 3.7s   

    2015-05-29 10:02:18 (1.05 MB/s) - ‘2.99.1.zip’ saved [4108685/4108685]

    gentoo-maniac ~ # sha256sum 2.99.1.zip 
    a0b5f4d444f720f4d1ccb4809276c03e4ed35adde11a180680a53d2c46b62460  2.99.1.zip

**Comment by Heather** [comment]
@andy-graprof yes, tarball is changed, I will fix it soon

**Comment by andy-graprof** [comment]
thanks :)

**Comment by Heather** [comment]
here: https://github.com/gentoo/dotnet/commit/4f6c7b9ecd5debdac131c5f31eadc834284c8a22
