### ISSUE TITLE
Can not mask mono-4

### ISSUE THREAD

**Issue by kayvax** [gentoo/dotnet#62]
Hi,
for some time I have problems with mono-4 from dotnet overlay. I can not mask it in any way and it breaks packages as mono-4 has removed lower targets. 

I have tried asking for help at Funtoo forums and #funtoo @Freenode but maintainers could not find way to mask it.

Whole topic:
http://forums.funtoo.org/topic/491-mask-problems/

Should you need more info I will try to provide it.
best regards,
kayvax

**Comment by kernelOfTruth** [comment]
When masking a higher version always go with regexp or wildcards:

Give the following a try:

```
=dev-lang/mono-4*
```

```
>=dev-lang/mono-4*
```

alternatively you could add the overlay:

```
=dev-lang/mono-4*::dotnet
```

```
>=dev-lang/mono-4*::dotnet
```

not sure if that works though.


If you only need newer versions of mono instead of all the other dotnet libraries, consider copying those over to your local overlay (e.g. /usr/local/portage) and keep them there, then removing the dotnet-overlay

**Comment by kayvax** [comment]
All you advised was tried earlier and did not work. Such masks are overruled by: 
/var/lib/layman/dotnet/profiles/package.unmask (or wherever one has layman configured)

cat package.unmask
dev-lang/mono
virtual/monodoc

dev-dotnet/gtk-sharp
dev-dotnet/gnome-sharp

This successfully permits any mask of this packages from dotnet overlay and I think it is outright wrong. If not for clue from funtoo forum I would never guessed that such thing could happen. 

Could you please take a look on dotnet/profile/package.unmask and just check whether it needs to be in such way?

best regards,
kayvax

**Comment by Heather** [comment]
Thank you for report, resolved in previous commit, I should also check for other unmasked packages. I'm using 9999 and it works fine and I had not tested the mask.

Check if it will install last 3.x `mono` from this overlay, 4.0.x is currently masked here https://github.com/gentoo/dotnet/blob/master/profiles/package.mask#L3

**Comment by Heather** [comment]
@kayvax this repository is mirror, I will push it to layman some later. for now you can just pull from it

**Comment by kayvax** [comment]
thank you.
