### ISSUE TITLE
mono-9999.ebuild - remove systemweb.patch

### ISSUE THREAD

**Issue by ArsenShnurkov** [gentoo/dotnet#69]
"https://github.com/gentoo/dotnet/blob/master/dev-lang/mono/mono-9999.ebuild
Please, fix build. systemweb.patch is no longer needed"
said outcastgit - https://github.com/outcastgit

I havn't rechecked this myself yet

**Comment by Heather** [comment]
@ArsenShnurkov someone need to check it, maybe I will, thanks

**Comment by outcastgit** [comment]
This is end of build.log

Makefile:406: ../../build/deps/System.Web_standalone_test_net_4_5.dll.makefrag: No such file or directory
Makefile:407: ../../build/deps/net_4_5_standalone-runner-support.dll.makefrag: No such file or directory
Makefile:427: warning: overriding recipe for target 'clean-local'
../../build/library.make:218: warning: ignoring old recipe for target 'clean-local'
Creating ../../build/deps/net_4_5_standalone-runner-support.dll.makefrag ...
Creating ../../build/deps/System.Web_standalone_test_net_4_5.dll.makefrag ...
Creating the per profile list ../../build/deps/net_4_5_System.Web.dll.sources ...
Makefile:427: warning: overriding recipe for target 'clean-local'
../../build/library.make:218: warning: ignoring old recipe for target 'clean-local'
Makefile:427: warning: overriding recipe for target 'clean-local'
../../build/library.make:218: warning: ignoring old recipe for target 'clean-local'
Read in 36 resources from '/var/tmp/portage/dev-lang/mono-9999/work/mono-9999/mcs/class/System.Web/resources/TranslationResources.resx'
Writing resource file...  Done.
Makefile:427: warning: overriding recipe for target 'clean-local'
../../build/library.make:218: warning: ignoring old recipe for target 'clean-local'
Makefile:427: warning: overriding recipe for target 'clean-local'
../../build/library.make:218: warning: ignoring old recipe for target 'clean-local'
mkdir -p -- ../../class/lib/net_4_5/plainweb/
MCS     [plainweb/net_4_5] System.Web.dll
../System.Web.Routing/System.Web.Routing/RouteCollection.cs(99,15): error CS0102: The type `System.Web.Routing.RouteCollection' already contains a definition for `AppendTrailingSlash'
../System.Web.Routing/System.Web.Routing/RouteCollection.cs(96,15): (Location of the symbol related to previous error)
../System.Web.Routing/System.Web.Routing/RouteCollection.cs(100,15): error CS0102: The type `System.Web.Routing.RouteCollection' already contains a definition for `LowercaseUrls'
../System.Web.Routing/System.Web.Routing/RouteCollection.cs(95,15): (Location of the symbol related to previous error)
Compilation failed: 2 error(s), 0 warnings
../../build/library.make:282: recipe for target '../../class/lib/net_4_5/plainweb/System.Web.dll' failed
make[11]: *** [../../class/lib/net_4_5/plainweb/System.Web.dll] Error 1
Makefile:295: recipe for target '../../class/lib/net_4_5/plainweb/System.Web.dll' failed
make[10]: *** [../../class/lib/net_4_5/plainweb/System.Web.dll] Error 2
Makefile:62: recipe for target '../../class/lib/net_4_5/plainweb/System.Web.dll' failed
make[9]: *** [../../class/lib/net_4_5/plainweb/System.Web.dll] Error 2
Makefile:291: recipe for target '../../class/lib/net_4_5/System.Web.Services.dll' failed
make[8]: *** [../../class/lib/net_4_5/System.Web.Services.dll] Error 2
../../build/rules.make:143: recipe for target 'do-all' failed
make[7]: *** [do-all] Error 2
../build/rules.make:170: recipe for target 'all-recursive' failed
make[6]: *** [all-recursive] Error 1
build/rules.make:170: recipe for target 'all-recursive' failed
make[5]: *** [all-recursive] Error 1
Makefile:46: recipe for target 'profile-do--net_4_5--all' failed
make[4]: *** [profile-do--net_4_5--all] Error 2
Makefile:42: recipe for target 'profiles-do--all' failed
make[3]: *** [profiles-do--all] Error 2
Makefile:545: recipe for target 'all-local' failed
make[2]: *** [all-local] Error 2
make[2]: Leaving directory '/var/tmp/portage/dev-lang/mono-9999/work/mono-9999_build/runtime'
Makefile:517: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/var/tmp/portage/dev-lang/mono-9999/work/mono-9999_build'
Makefile:446: recipe for target 'all' failed
make: *** [all] Error 2
 .[31;01m*.[0m ERROR: dev-lang/mono-9999::dotnet failed (compile phase):
 .[31;01m*.[0m   emake failed
 .[31;01m*.[0m
 .[31;01m*.[0m If you need support, post the output of `emerge --info '=dev-lang/mono-9999::dotnet'`,
 .[31;01m*.[0m the complete build log and the output of `emerge -pqv '=dev-lang/mono-9999::dotnet'`.
 .[31;01m*.[0m The complete build log is located at '/var/tmp/portage/dev-lang/mono-9999/temp/build.log'.
 .[31;01m*.[0m The ebuild environment file is located at '/var/tmp/portage/dev-lang/mono-9999/temp/environment'.
 .[31;01m*.[0m Working directory: '/var/tmp/portage/dev-lang/mono-9999/work/mono-9999_build'
 .[31;01m*.[0m S: '/var/tmp/portage/dev-lang/mono-9999/work/mono-9999'

**Comment by Heather** [comment]
testing to build with disabled patch

**Comment by ArsenShnurkov** [comment]
It will compile without patch (because it did that earlier), but sites may stop work in production, because patch can contain more fixes, than actually included into framework now.

**Comment by outcastgit** [comment]
Does someone use version fron SVN in productuin?

**Comment by outcastgit** [comment]
So may be add 4.0.2.5 version to overlay?

**Comment by ArsenShnurkov** [comment]
https://github.com/gentoo/dotnet/pull/70

**Comment by ArsenShnurkov** [comment]
I disagree with resolution, because there is no fixed version ebuilds, which apply the patch, and some sites use that functionality (that is why patch was applied in the first time) - they will stop work at the nearest update. So, now I am waiting for ebuild for mono 4.0.2.5

**Comment by outcastgit** [comment]
ArsenShnurkov, 9999 version is not for production.

**Comment by ArsenShnurkov** [comment]
@outcastgit, I will agree with you, if you will write a replacement

**Comment by outcastgit** [comment]
@ArsenShnurkov, i agree with you, that need beta version mono like night builds with patch. But i cannot create ebuilds yet. may be in future.

**Comment by ArsenShnurkov** [comment]
here is the point where patch was introduced - 
https://github.com/gentoo/dotnet/pull/51
here is the original source - https://github.com/mono/mono/pull/874

**Comment by Heather** [comment]
@ArsenShnurkov I reopen this issue for patch correction if someone will have time to work on it

**Comment by ArsenShnurkov** [comment]
I reopened my proposition - 
https://github.com/gentoo/dotnet/pull/70
