### ISSUE TITLE
ebuild for Monodevelop 5.9.5.5

### ISSUE THREAD

**Issue by ArsenShnurkov** [gentoo/dotnet#74]
This month's version was released 3 days ago:
https://github.com/mono/monodevelop/releases

**Comment by chalucha** [comment]
ebuild was merged with #77, so this can be closed

**Comment by ArsenShnurkov** [comment]
cool, i will check soon, and close if so

**Comment by Heather** [comment]
at least it builds fine for me

**Comment by ArsenShnurkov** [comment]
I successfully built this thing with
USE="git gnome subversion -doc -qtcurve"
on mono 4.0.2.5

     >>> dev-util/monodevelop-5.9.5.5 merged.

     >>> Recording dev-util/monodevelop in "world" favorites file...

didn't test the functionality of monodevelop yet.
