### ISSUE TITLE
mono-4.0.3.13, Argh!

### ISSUE THREAD

**Issue by ArsenShnurkov** [gentoo/dotnet#81]
https://github.com/mono/mono/releases/
released 8 hours ago

**Comment by Heather** [comment]
@ArsenShnurkov good so :)

**Comment by ArsenShnurkov** [comment]
sabayon package.use # mono -V
    Mono JIT compiler version 4.0.3 (Stable 4.0.3.13/429313d Mon Jul 20 19:05:37 MSK 2015)
    Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
    	TLS:           __thread
    	SIGSEGV:       altstack
    	Notifications: epoll
    	Architecture:  amd64
    	Disabled:      none
    	Misc:          softdebug 
    	LLVM:          supported, not enabled.
    	GC:            sgen

Smuxi-1.0 requires boehm instead of SGen (and boehm is default for Debian). I don't know how to switch them

**Comment by Heather** [comment]
@ArsenShnurkov so far we have no smuxi 1.0 in repo :(

**Comment by ArsenShnurkov** [comment]
https://github.com/mono/mono#configuration-options

The following are the configuration options that someone building Mono might want to use:

--with-sgen=yes,no - Generational GC support: Used to enable or disable the compilation of a Mono runtime with the SGen garbage collector.

On platforms that support it, after building Mono, you will have both a mono binary and a mono-sgen binary. mono uses Boehm, while mono-sgen uses the Simple Generational GC.

--with-gc=[included, boehm, none] - Selects the default Boehm garbage collector engine to use.

included: (slighty modified Boehm GC) This is the default value for the Boehm GC, and it's the most feature complete, it will allow Mono to use typed allocations and support the debugger.

boehm: This is used to use a system-install Boehm GC, it is useful to test new features available in Boehm GC, but we do not recommend that people use this, as it disables a few features.

none: Disables the inclusion of a garbage collector.
