### ISSUE TITLE
[dev-dotnet/gtk-sharp-gapi-2.12.10] CSC=/usr/bin/gmcs

### ISSUE THREAD

**Issue by ArsenShnurkov** [gentoo/dotnet#91]
Emerging (18 of 23) dev-dotnet/gtk-sharp-gapi-2.12.10::gentoo

<pre><code>>>> Compiling source in /var/tmp/portage/dev-dotnet/gtk-sharp-gapi-2.12.10/work/gtk-sharp-2.12.10 ...
make -j4 CSC=/usr/bin/gmcs 
make: /usr/bin/gmcs: Command not found
Makefile:516: recipe for target 'gapi-parser.exe' failed
make: *** [gapi-parser.exe] Error 127

# mono -V
Mono JIT compiler version 4.0.3 (Stable 4.0.3.13/429313d gtk-sharp-gapiMon Aug  3 22:35:49  2015)
</code></pre>

There is code in /usr/portage/gtk-sharp-module.eclass
<pre><code>gtk-sharp-module_src_compile() {
	rm -f "${S}"/Makefile* &> /dev/null
	cd "${S}/${GTK_SHARP_MODULE_DIR}"
	emake CSC=/usr/bin/gmcs || die "emake failed"
}</code></pre>

overlay have similar file, which is not patched in this place
https://github.com/gentoo/dotnet/blob/958b12f377e051df254451bc30f7e2a1a025c005/eclass/gtk-sharp-module.eclass#L544

But changing overlay's version is not enough, because gtk-sharp-gapi is located in the main tree (so we need to make copy of gtk-sharp-gapi to overlay, or to patch .eclass in the main tree)

the reason, why i didn't commit this change - I don't know how to check mono version in .eclass

**Comment by Heather** [comment]
@ArsenShnurkov `gtk-sharp-gapi` is part of `gtk-sharp` package now https://github.com/gentoo/dotnet/blob/master/dev-dotnet/gtk-sharp/gtk-sharp-2.99.1.ebuild#L27

**Comment by Heather** [comment]
by the way `https://github.com/mono/gtk-sharp/releases` it should be bumped to `2.99.3`
